name: Ridecount-System
version: '${version}'
description: Ridecount-System fuer Train-Schilder

main: de.skyforce.main.ridecountsystem.RidecountSystem
api-version: '1.21'
load: POSTWORLD
softdepend: [Train_Carts, TCCoasters]

commands:
  ridecount:
    description: Verwalte Ridecount-Statistiken
    usage: /ridecount <show|clear> <spieler> [attraktion]
    permission: ridecount.admin

permissions:
  ridecount.admin:
    description: Zugriff auf Ridecount-Admin-Commands
    default: op
  ridecount.sign.create:
    description: Erlaubt das Erstellen von Ridecount-Schildern
    default: op
